### ISSUE TITLE
How to run with the dataset for graph classification?

### ISSUE THREAD

**Issue by Billy1900** [LiZhang-github/LA-GCN#1]
I read your code, but it might be for node classification. Your paper mentioned graph classification, how can I reproduce it?

**Comment by LiZhang-github** [comment]
Hi  Nanqing Luo,

Thanks for your interest in our work. The current version of our code is
just for node classification, and we will update and give more detailed
information.

For graph classification, you just need to sum or average all the learned
node embeddings to do the graph classification task.

Best
Li
